config/routes.rb
Rails.application.routes.draw do
  resources :homes
	root :to => "user_details#new"
	# root :to => "user_details#new" use this for paymment gateway
	# match 'Plot-booking' => 'user_details#new', :as => :root
	get "Plot-booking", to: "user_details#new"
	post "Plot-booking-confirmation",to:  "user_details#create"
	# get "Plot-booking/confirmation",to: "payments#edit"
	get '/confirmation/:id' => 'user_details#edit', as: 'plot_booking_confirmation_success'
	get '/confirmation/redirect/:id' => 'user_details#redirect', as: 'plot_booking_confirmation_redirect'
	get '/thank-you/:id' => 'user_details#thankyou', as: 'plot_booking_thank_you'
	post '/sitevisit-datetime',to: "user_details#create_site_visit_lead"


 

	# get "Plot-booking/confirmation", to: "user_details#edit" 

	# root :to => 'homes#index'
	#get "about-us",to: "homes#aboutus"
	#get "about-oragadam",to: "homes#about_oragadam"
	#get "plots-oragadam",to: "homes#plots_oragadam"
	#get "apartment", to: "homes#apartment"
	#get "amenities",to: "homes#amenities"
	#get "rental", to: "homes#rental"
	#get "commercial-retail",to: "homes#commercial_retail"
	#get "contact-us", to: "homes#contact_us"
	#get "testimonial", to: "homes#testimonial"
	#get "policies", to: "homes#policies"
	#get "sitemap.xml", to: "homes#sitemap", :defaults => {:format => 'xml'}
	#get "site-map.html", to: "homes#sitemap2"
	# root :to => "user_details#create"
	

	# post "transaction/ccavRequestHandler",to: "payments#requestHandler"
	get "/transaction/ccavRequestHandler",to: "payments#requestHandler"

	get "/success",to: "payments#finish"
	post "/transaction/ccavResponseHandler",to: "payments#responseHandler"
	# resources :camp_leads
	post "/camp_lead/new", to: "camp_leads#create"
	post "/enquire_lead/new", to: "enquire_leads#create"
	post "/linkdin_lead/new", to: "linkdin_leads#create"
	get "/report-data", to: "camp_leads#index"

  # resources :payments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
    has_many :orders
	validates :phone_number,:presence => true,
                 :numericality => true,
                 :length => { :minimum => 10, :maximum => 20 }
    validates :plot_details,:presence => true 
    def self.to_csv(options = {})
    	CSV.generate(options) do |csv|
    		csv << column_names
    		all.each do |camp_leads|
    			csv << camp_leads.attributes.values_at(*column_names) 
    		end
    	end
	end
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
skip_before_action :verify_authenticity_token
def new
	@plots = PlotSize.all
	@user_detail = UserDetail.new
	
	# @some = {}
	# @arr = ["vvv=karthik","age=asasas","occ=software"]
	# @arr.each do |key|
	# 	binding.pry
 #        @some["#{key.from(0).to(key.index("=")-1)}"] = "#{key.from(key.index("=")+1).to(-1)}"
 #      end
 #      binding.pry
 #      @order_id = @some["vvv"]
 #       binding.pry
end
def redirect
	# binding.pry
	redirect_to controller: 'payments', action: 'requestHandler', id: params[:id] 
end
def create
	# binding.pry
	@user_detail = UserDetail.new(user_detail_params)
	# binding.pry
	if @user_detail.save

		# binding.pry
		############use this if paymet needed############
		PaymentMailer.lead_registration(@user_detail).deliver_later
		PaymentMailer.lead_post(@user_detail).deliver_later
		# redirect_to plot_booking_confirmation_success_path(@user_detail)
		############# end cuurent prodution down #############################
		# PaymentMailer.lead_registration(@user_detail).deliver_now
		# PaymentMailer.lead_post(@user_detail).deliver_now
		redirect_to plot_booking_thank_you_path(@user_detail)
		##################################################
		# redirect_to controller: 'payments', action: 'requestHandler', order_id: @user_detail[:id] 
 
	else
		# binding.pry
		@user_detail.errors.full_messages.each do |key|
			flash[:warning] = key
		end
		# flash[:warning] = "Contact phone_number should be minimum 10 to maximum 15 digits"
		redirect_to action: 'new'
	end
	
		@data = { api_key: "1bd54866736339b8f49efe4cbd3404b8",
				sell_do: {
					form: {
						lead: {
							first_name: @user_detail[:name],
							last_name: "",
							email: @user_detail[:email],
							phone: "+91#{@user_detail[:phone_number]}"
							# project_id: "56659cb03bb2f8f46900001b"
							},
						note:{
							content:  @user_detail[:queries]
							},
						address:{
							address1: "",
							address2: "",
							country: "India",
							state: "tamilnadu",
							city: "city",
							zip: "0"
							},
						requirement:{
							property_types: [@user_detail[:plot_details]],
							locations: [],
							bhk: ["2","2.5"],
							min_budget: 0,
							max_budget: 0,
							min_possession: "",
							max_possession: ""
							}
						},
						campaign: {
							 srd: "5b2793ea923d4a68368cb3b6" 
						}
					# sell_do: { campaign: { srd: "5b2793ea923d4a68368cb3b6" }}
					}
				}
			@response = HTTParty.post('https://app.sell.do/api/leads/create',
			{ 
    			:body => @data.to_json,
    			:headers => { 'Content-Type' => 'application/json', 'Accept' => 'application/json'}
  			});	
  			# binding.pry

  			
end
def edit
	# binding.pry
	 @user_detail = UserDetail.find(params[:id])
	 	# binding.pry
end
## Remove this thankyou if original payment comes################
def thankyou
	@user_detail = UserDetail.find(params[:id])
end

def new_site_visit_lead
	@sitevisit_lead = SitevisitLead.new
end
def create_site_visit_lead
	@sitevisit_lead = SitevisitLead.new(sitevisit_lead_params)

	if @sitevisit_lead.save
		PaymentMailer.site_visit_mail(@sitevisit_lead).deliver_later
	else
		render 'new_site_visit_lead'
	end
end

private
  def user_detail_params
    params.require(:user_detail).permit(:name, :email, :plot_details,:phone_number,:payment_status,:description)
  end	
  def sitevisit_lead_params
    params.require(:sitevisit_lead).permit(:site_visit_date_time, :name, :email, :plot_details,:phone_number,:payment_status,:description)
  end	

end

app/views/user_details/edit.html.erb
<%= content_for(:title, "Hiranandani Parks - Plot Booking | Oragadam, Chennai") %>
<%= content_for(:description, "Hiranandani Parks is a mega township with all Lifestyle Amenities at Oragadam-Chennai by Hiranandani Communities under leadership of Niranjan Hiranandani.") %>
<%= content_for(:keyword, "Hiranandani Parks, Mega Township at Oragadam  Chennai, Mega Township at Chennai suburb, Hiranandani Parks at Oragadam Chennai, Hiranandani Parks by Hiranandani Communities, Hiranandani Communities, Niranjan Hiranandani Initiative, Township by Niranjan Hiranandani, Hiranandani Parks by Hiranandani Communities, Oragadam Residences, Peaceful Residences at Oragadam Chennai, Township by Hiranandani Communities, Township by Hiranandani Communities at Oragadam Chennai, Township with all lifestyle amenities, Luxury Residences at Oragadam Chennai, Residences with Premium Amenities, Residences with Club House and Gymnasium, Residences with Swimming Pool, Township with Luxury Amenities, Township with Golf Course, Township with Club House, Hiranandani Township in Chennai, Niranjan Hiranandani instead Niranjan Hiranandani Initiative, Niranjan Hiranandani's projects, Hiranandani's in Chennai, 2,2.5,3 BHK in Oragadam, 2,2.5,3 BHK in Chennai, Plots and Villas in Oragadam, Hiranandani's plots in Chennai, Hiranandani villa in Chennai, Township with cricket in chennai, Township by Hiranandani Group at Chennai, Township with Music academy in Chennai,Free plots in chennai,Individual villas in chennai,Plots in OMR,Plots in chennai outer,Plots in oragadam,Plot in hiranandani,Plots at low rate chennai,600 square feet Plots in chennai,1200 square feet Plots in chennai,Free movie tickets,Best real estate in chennai,Best builders in chennai,India no 1 builders,constructural industry with low rate in chennai,Plots under 1000000") %>
<section style="background-color: #121212;margin-top: 56px;">
	<div class="container" style="min-height: 500px;">
		<div class="row" style="margin-top: 70px;">
			<div class="col-md-12">
				<div class="text-center">
					<%= image_tag("line-top.png", :alt => "hiranandani-image") %>

						<h1>Hello <%= @user_detail.name %>, Thank you for booking plot with us.</h1>
						<!-- <h3>Oragadam, Chennai</h3> -->
					<%= image_tag("line-bottom.png", :alt => "hiranandani-image") %>
				</div>
			</div>
		</div>
		<!-- <div class="col-md-12"> -->
			<!-- <h3>Your plot details <%= @user_detail.plot_details %></h3> -->
		<!-- </div> -->
		<div class="col-md-12 text-center">
			<h2>Do you confirm your booking by paying Rs.20000/ through online ?</h2>
			<h2>Please click the below button to confirm your plot.</h2>
			<div class="col-md-12">
				 <%= link_to "Click here to pay", plot_booking_confirmation_redirect_path(@user_detail),class:'btn custom-btn btn-lg'  %>
				
			</div>
		</div>
	</div>
</section>

<style type="text/css">
	.custom-btn{
	background-color: #f0ad4e;
    border-color: #eea236;
    color: #fff;
}
</style>

app/views/user_details/redirect.html.erb
<section class="bg-about" style="margin-top: 50px;">
	<div class="row" style="min-height: 300px;">
		<div class="col-md-12 text-center">
			<h3>Loading....Please wait</h3>
			<img src="https://s3.amazonaws.com/aws-website-hiranandani-z52b5/images/hira-img/loading-1.gif" width="200" />
		</div>
	</div>
</section>

app/views/user_details/thankyou.html.erb
<%= content_for(:title, "Hiranandani Parks - Thanks | Oragadam, Chennai") %>
<%= content_for(:description, "Hiranandani Parks is a mega township with all Lifestyle Amenities at Oragadam-Chennai by Hiranandani Communities under leadership of Niranjan Hiranandani.") %>
<%= content_for(:keyword, "Hiranandani Parks, Mega Township at Oragadam  Chennai, Mega Township at Chennai suburb, Hiranandani Parks at Oragadam Chennai, Hiranandani Parks by Hiranandani Communities, Hiranandani Communities, Niranjan Hiranandani Initiative, Township by Niranjan Hiranandani, Hiranandani Parks by Hiranandani Communities, Oragadam Residences, Peaceful Residences at Oragadam Chennai, Township by Hiranandani Communities, Township by Hiranandani Communities at Oragadam Chennai, Township with all lifestyle amenities, Luxury Residences at Oragadam Chennai, Residences with Premium Amenities, Residences with Club House and Gymnasium, Residences with Swimming Pool, Township with Luxury Amenities, Township with Golf Course, Township with Club House, Hiranandani Township in Chennai, Niranjan Hiranandani instead Niranjan Hiranandani Initiative, Niranjan Hiranandani's projects, Hiranandani's in Chennai, 2,2.5,3 BHK in Oragadam, 2,2.5,3 BHK in Chennai, Plots and Villas in Oragadam, Hiranandani's plots in Chennai, Hiranandani villa in Chennai, Township with cricket in chennai, Township by Hiranandani Group at Chennai, Township with Music academy in Chennai,Free plots in chennai,Individual villas in chennai,Plots in OMR,Plots in chennai outer,Plots in oragadam,Plot in hiranandani,Plots at low rate chennai,600 square feet Plots in chennai,1200 square feet Plots in chennai,Free movie tickets,Best real estate in chennai,Best builders in chennai,India no 1 builders,constructural industry with low rate in chennai,Plots under 1000000") %>
<section class="bg-about">
	<div class="container" style="padding-top: 100px; padding-bottom: 100px;margin: auto;text-align: center;  ">
		<div class="row">
			<div class="wrap">
				<!-- <img src="line-top.png" alt="hiranandani-image"> -->
				<%= image_tag("line-top.png", :alt => "hiranandani-image") %>
					<h1>Hello <%= @user_detail.name.camelize %></h1>
					<h2>Thank You we will be calling you soon..!</h2>
					<!-- <h3>Oragadam, Chennai</h3> -->
				<!-- <img src="line-bottom.png" alt="hiranandani-image"> -->
				<%= image_tag("line-bottom.png", :alt => "hiranandani-image") %>
			</div>
		</div>
		<!-- <div class="row" > -->
		  <div class="col-md-12" style="padding-top: 20px; text-align: center;margin: auto;">
			
			<h5 style="padding-top: 20px;padding-bottom: 10px;">Having Trouble? <a href="https://hiranandaniparks.com/contact-us.html">Contact Us</a></h5>
		  </div>
		  	<a  href="https://hiranandaniparks.com"><button type="button" class="btn btn-warning">Continue To Homepage</button></a>
		  	<br><br>
		  	<button class="btn btn-warning open-site-visit">Book site visit</button>
		</div>

	</div>
	
  <div class="site-visit-container">
  	<div class="">
  		<div class="text-center">
				<div>
					<h4>Site Visit Date and Time:</h4>
					<div class="site_visit_date_hidden">
						<label class="name"><%= @user_detail.name %></label>
						<label class="email"><%= @user_detail.email %></label>
						<label class="phonenum"><%= @user_detail.phone_number %></label>
						<label class="plot_details"><%= @user_detail.plot_details %></label>
					</div>  
					<div>
						<div class='input-group date' id='datetimepicker1'>
			  			<input type='text' class="form-control" name="site_visit_date" required/>
						    <span class="input-group-addon">
						      <span class="glyphicon glyphicon-calendar"></span>
						    </span>
						</div>
						<button class="btn btn-warning ssl_submit">Submit</button>
						<p>* Free Pick-up and Drop</p>
					</div>
	      </div>		
	  	</div>
  	</div>
		<script type="text/javascript">
		  $(function () {
		    $('#datetimepicker1').datetimepicker();
		  });

		  function send_sitevisit_lead(){
		  	var data = {"sitevisit_lead": {
                    "name": $(".name").text(),
                    "email": $(".email").text(),
                    "phone_number" : $(".phonenum").text(),
                    "plot_details" : $(".plot_details").text(),
                    "site_visit_date_time": $("input[name=site_visit_date]").val(),
                	}
					};
					debugger
				$.ajax({
				  type: "POST",
				  url: location.origin+"/Plot-booking/sitevisit-datetime",
				  header:{"content-type": "application/json"},
				  data: data,
				  success: function(data){
				  			alert("You have successfully booked site visit.  Our executives will contact you soon.");
				  			location.reload();
				  			// window.location="linkedin-campaign-thankyou.html";
					    },

					    error: function(data){
					       // window.location="linkedin-campaign-thankyou.html";
					       alert("Our service time is between 10pm to 6am");
					       location.reload();
					    }
				});		
		  }
		  $('.open-site-visit').click(function(){
		  	$('.site-visit-container').fadeIn();
		  });
		  $('.ssl_submit').click(function(){
		  	send_sitevisit_lead();
		  });
		</script>
  </div>

</section>